import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="bg-gradient-to-r from-blue-500 to-purple-500 bg-clip-text">
          <h1 className="text-9xl font-extrabold text-transparent my-4">
            Next.js + Strapi
          </h1>
        </div>
      </main>
    </>
  );
}
